### PR TITLE
Refactored (base) classes from init.py into separate files

### LINKED ISSUE #359: Base classes in separate files
In #309 some base classes were moved into the corresponding `__init__.py` files for consistency reasons. This lead to circular imports which needed to be fixed in #331. However, the circular imports could have been avoided with having the definitions of base classes in separate files and not in the `__init__.py` files. 

Therefore, moving all base class definitions into separate files would make sense.

### PR DESCRIPTION
**Pull request by TomTomRixRix**
**Please check the following before creating the pull request (PR):**
- [x] Did you run automatic tests?
- [x] Did you run manual tests?
- [ ] Is the code provided in the PR still backwards compatible to previous SIMPA versions?
**The provided code is not backwards compatible anymore as we changed a lot of file names and class names.**
 
**Additional context (e.g. papers, documentation, blog posts, ...)**
Idea for the refactoring came from @RecurvedBow   

**List any special testing requirements**
Please also check the documentation if this is still correct and working

 **Provide issue / feature request fixed by this PR**
 
 Fixes #359

### CODE REVIEW

**Comment by TomTomRixRix** [comment]
While refactoring all the classes I've found some **naming inconsistencies** which we could also resolve in this PR. For example currently we sometimes calls the base classes of adapters `XXXBaseAdapter` and sometimes `XXXAdapterBase`. Ideally this would be _consistent_ and so that also the file names would be named consistently as they should have the same name as the classes. 

When do we add `Base` in the class name`? For example, we call the `DigitalDeviceTwinBase` and `AcousticForwardModelBaseAdapter` but the `SimulationModule` and `PipelineModule` don't contain `Base`.

Another naming issue that I realized concerns the simulation modules. The 4 modules are called `acoustic_forward_module`, `optical_simulation_module`, `reconstruction_module` and `volume_creation_module`. Is there a reason why we use `forward_module` for the acoustic step and `simulation_module` for the optical step? 

This gets even more messy when looking at the individual adapters. For example, there is a `AcousticForward**Model**BaseAdapter` and the KWaveAdapter in the `acoustic_forward_**module**_k_wave_adapter.py`. In my opinion we should either stick to **module or forward model**, but not a mixture.  Interestingly, the `OpticalForwardModuleBase` does not even contain `Adapter` in its name and is a `Module` and not a `Model` as for the acoustic step.

Furthermore, the file names and sometimes also the class names are very **repetitive**, e.g. all file names in the `optical_simulation_module`  start with `optical_forward_model_` which should be clear by the path. My suggestion would be to only call the files for example `mcx_adapter.py` which we partly already do for the class names, e.g. `MCXAdapter`. As the adapter inherits from the optical base adapter, it should be clear that it is an optical adapter and similar for the file names. Only for the base adapters it might make sense to call them OpticalBaseAdapter although this should ideally also be clear by the import statements.

My **suggestions**, but I'm open for other suggestions, would be:
* call the simulation modules  `{acoustic, optical, reconstruction, volume_creation}_module`, leaving out the `forward` or `simulation` and calling them `modules` and not `model`. 
* call the base classes of adapters `XXXBaseAdapter`, e.g. `OpticalBaseAdapter` 
* have file names such as `core/simulation_modules/optical_module/mcx_adapter.py` and class definitions `MCXAdapter(OpticalBaseAdapter)`
* either all classes which contain abstract methods should contain `Base` in their name or none of them should contain `Base`. Either `SimulationModuleBase` and `OpticalBaseAdapter` or simply `SimulationModule` and `OpticalAdapter`. I would prefer mentioning explicitly the `Base` in the name so that the reader is made aware that there are abstract methods to be implemented.

**Comment by kdreher** [comment]
I fully agree that making all the naming consistent makes a lot of sense!

- I like your proposed naming convention: `{acoustic, optical, reconstruction, volume_creation}_module` for the file names of the simulation modules
- I would call the base classes `XXXAdapterBase`, e.g. `OpticalAdapterBase` to make clear that they are parent classes
- Shortening the file names and class definitions also sounds good
- I agree that the base classes are more self-explanatory if they contain `Base`. So I would also add that to `SimulationModule` and `PipelineElement`, e.g. `PipelineElementBase`

**Comment by TomTomRixRix** [comment]
✔️ We've now updates the file and class names accordingly:
* in `pipeline_element_base.py` there now is a `PipelineElementBase` class
* in `simulation_module_base.py` there now is a `SimulationModuleBase` class
* there are `{acoustic, optical, reconstruction, volume_creation}_module` folders with each of them having an `XXXAdapterBase` class in the `xxx_adapter_base.py` file
* adapter names are shortened, e.g. `DelayAndSumAdapter` class in the `reconstruction_module/delay_and_sum_adapter.py` and class and file names are consistent.

🔧 Furthermore we noticed two failing manual tests which we quickly fixed. There was only a mismatch of the temporal spacing given to the reconstruction convenience functions.

🚧  During the renaming we noticed **further inconsistencies** which we could eliminate. @kdreher, getting your opinion on these choices would be helpful:
1. Currently we have `SimulationModules`, `ProcessingComponents` and `PipelineElements`. What is the difference between *modules*, *components* and *elements*? Maybe naming them consistently would make more sense. I would suggest to use *components* as this would be consistent with the *component settings*.
2. The file names of the base classes are currently similar to the class names, e.g. `OpticalAdapterBase` in `optical_module/optical_adapter_base.py` and `SimulationModuleBase` in `simulation_module/simulation_module_base.py`. For the base classes it would perhaps make sense to just call the files `base.py` as it should be obvious to which module they belong and thus reduce the file name length. On the other hand then the file and class names are not entirely consistent anymore. This probably depends a lot on personal preference.
3. Currently we didn't apply the renaming to the `simpa_examples` and `simpa_tests`. There might be some tests where which we called `AcousticForwardModelTest` or similar. It would probably make sense to also update the naming so that it is consistent with the one in `core`, right?

 ⚠️  We didn't build and update the documentation yet. This should be done and tested before merging.

**Comment by kdreher** [comment]
1. We deliberately chose the names `SimulationModules`, `ProcessingComponents` and `PipelineElements`. A `SimulationModule` is one of the four steps in the PA simulation pipeline. Each of them can only occur once in a pipeline as simulating eg. the acoustic wave propagation wouldn't make sense for a single simulation volume. `ProcessingComponents` are components that can be used once or multiple times at different stages during the simulation pipeline. `PipelineElements` is the umbrella term or base class for both of them because programmatically, they should have a similar class structure.
2. Yes, I think this is a personal preference thing. For me personally, I would prefer keeping the names as is because if I'm working on multiple base classes at the same time in any IDE, I can differentiate the different files by file name where I would need to look up the base path otherwise.
3. I agree that it might make sense to rename some tests and examples. For example right now, we have multiple examples that start with "minimal" where it's probably more sensible to have only one true minimal example.

**Review by jgroehl — APPROVED** [review]
Amazing refactoring effort! Thanks :)

**Review by kdreher — APPROVED** [review]

**Pull request merged**
