### PR TITLE
Additional executable flags

### LINKED ISSUE #9: Add possbility to add extra flags for the simulation executables

### PR DESCRIPTION
**Pull request by TomTomRixRix**
New PR for #9 instead of PR #168

 **Please check the following before creating the pull request (PR):**
- [x] Did you run automatic tests?
- [ ] Did you run manual tests?
- [x] Is the code provided in the PR still backwards compatible to previous SIMPA versions?
  
 **List any specific code review questions**
@leoyala Can the new `Tags.ADDITIONAL_FLAGS` option be used to provide some of the command line options in the MCX reflectance adapter?

 **List any special testing requirements**
Some of the additional flags might break simulations, e.g. `-v` for MCX just prints the version and doesn't run the simulation. 

 **Provide issue / feature request fixed by this PR**
 
 Fixes #9

### CODE REVIEW

**Comment by leoyala** [comment]
I think that a better way to deal with additional flags would be such that the additional flags defined by the user take priority over the default flags that are defined on each module. For example, if the default flags are `-F jnii`, and the user passes `-F mc2`, then the one defined by the additional flags should take priority.

**Comment by TomTomRixRix** [comment]
> I think that a better way to deal with additional flags would be such that the additional flags defined by the user take priority over the default flags that are defined on each module. For example, if the default flags are `-F jnii`, and the user passes `-F mc2`, then the one defined by the additional flags should take priority.

Although it is not necessarily always the case, usually if a flag is given multiple times the last given flag argument is considered. Thus our current implementation already allows for overriding existing flags as the additional flags are added at the end. We tested that this works at least for MCX and MATLAB and added this information to the documentation of `Tags.ADDITIONAL_FLAGS`

**Comment by leoyala** [comment]
> > I think that a better way to deal with additional flags would be such that the additional flags defined by the user take priority over the default flags that are defined on each module. For example, if the default flags are `-F jnii`, and the user passes `-F mc2`, then the one defined by the additional flags should take priority.
> 
> Although it is not necessarily always the case, usually if a flag is given multiple times the last given flag argument is considered. Thus our current implementation already allows for overriding existing flags as the additional flags are added at the end. We tested that this works at least for MCX and MATLAB and added this information to the documentation of `Tags.ADDITIONAL_FLAGS`

Ok that sounds good, I would say lets add that information in the docs then; otherwise users will not know that they can define additional flags

**Comment by TomTomRixRix** [comment]
Similar test for MATLAB in kWaveAdapter is still missing

**Comment by leoyala** [comment]
Is this ready for a new round of reviews? :)

**Comment by TomTomRixRix** [comment]
> Is this ready for a new round of reviews? :)

I've added the missing test, now it's ready for a new round of reviews, @kdreher

**Review by jgroehl — DISMISSED** [review]

**Review by jgroehl — APPROVED** [review]

**Review by kdreher — APPROVED** [review]

**Pull request merged**
