### PR TITLE
Structure creation on GPU

### PR DESCRIPTION
**Pull request by TomTomRixRix**
Solves issue #166 

The structures are now created using PyTorch instead of NumPy. Therefore, the input values were converted into torch tensors with float32 precision. NB: NumPys default precision was float64.
For compatibility reasons each structure generator still returns a Numpy array.

Depending on the user settings and hardware availability processing is done on GPU or CPU, as described in #169

### CODE REVIEW

**Review by kdreher — CHANGES_REQUESTED** [review]
Currently, after the adapter is done with the volume creation, the space on the GPU that was needed for all the tensors is not freed again. The memory is still allocated until the whole script is ended. Only then, is it freed up again.

**Comment by TomTomRixRix** [comment]
I'm not calling `torch.cuda.empty_cache()` at the end of volume creation. Furthermore, no tensors are saved in structure params anymore as this caused blocking of some GPU memory because they were still referenced in structure objects.

I've also fixed a bug in the vessel structure caused by random variable drawing. This only occurred in random occasions that's probably why it wasn't detected before.

**Review by kdreher — APPROVED** [review]
looks good to me

**Comment by kdreher** [comment]
closes #166

**Pull request merged**
