### PR TITLE
KWave adapter rotation bug fix

### LINKED ISSUE #264: Possible Bug: Rot90 in kwave adapter
**Describe the bug**
The kwave adapter uses rot90 to orient the images/volumes for the kwave axis convention.
But rot90 does not preserve the original positions in the image.
This is because np.arrays origin is the top-left corner and rot90 maps this corner to top-right, instead preserving it at the top left. 

Here an example based optical_and_acoustic_simulation.py, where the sensor position and vessel position are set to VOLUME_TRANSDUCER_DIM_IN_MM/3 (not in the middle as before): 
bug
In the original slice the vessel sits at index 125. After rot90 it sits at index 250. Intead transpose would be the correct behaviour.

By looking the p0 map and the sensor in kwave we can see that this unaligns sensor and the properties:
p0_sensor

 **Specify a priority (low, medium, high)**
high

**To Reproduce**

-> optical_and_acoustic_simulation.py

-  tissue_dict["vessel_1"] = sp.define_circular_tubular_structure_settings(
      tube_start_mm=[VOLUME_TRANSDUCER_DIM_IN_MM/3, 0, 5],
      tube_end_mm=[VOLUME_TRANSDUCER_DIM_IN_MM/3, VOLUME_PLANAR_DIM_IN_MM, 5],
      molecular_composition=sp.TISSUE_LIBRARY.blood(),
      radius_mm=2, priority=3, consider_partial_volume=True,
      adhere_to_deformation=False
  )
- delete vessel_2

- device = sp.PhotoacousticDevice(device_position_mm=np.array([VOLUME_TRANSDUCER_DIM_IN_MM/3,
                                                             VOLUME_PLANAR_DIM_IN_MM/2,
                                                             0]),
                                field_of_view_extent_mm=np.asarray([-15, 15, 0, 0, 0, 20]))

**Additional context**
Solution:
-> acoustic_forward_module_k_wave_adapter.py

  data_dict[Tags.DATA_FIELD_SPEED_OF_SOUND] = data_dict[Tags.DATA_FIELD_SPEED_OF_SOUND][image_slice].T
  data_dict[Tags.DATA_FIELD_DENSITY] = data_dict[Tags.DATA_FIELD_DENSITY][image_slice].T
  data_dict[Tags.DATA_FIELD_ALPHA_COEFF] = data_dict[Tags.DATA_FIELD_ALPHA_COEFF][image_slice].T
  data_dict[Tags.DATA_FIELD_INITIAL_PRESSURE] = data_dict[Tags.DATA_FIELD_INITIAL_PRESSURE][image_slice].T

### PR DESCRIPTION
**Pull request by TomTomRixRix**
I switched `rot90` to `transpose` transformation and deleted the reverse ordering of sensor elements in time series data.

So far not test have been run. It might make sense to implement additional tests for avoiding such bugs.

 **Please check the following before creating the pull request (PR):**
- [x] Did you run automatic tests?
- [x] Did you run manual tests?
- [x] Is the code provided in the PR still backwards compatible to previous SIMPA versions?
  
 **List any specific code review questions**
  
 **List any special testing requirements**
 Please also test 3D case, this hasn't been done so far.

 **Additional context (e.g. papers, documentation, blog posts, ...)**
  
 **Provide issue / feature request fixed by this PR**
 
 Fixes #264

### CODE REVIEW

**Comment by TomTomRixRix** [comment]
Currently manual test `simpa_tests/manual_tests/acoustic_forward_models/KWaveAcousticForwardConvenienceFunction.py` fails, see #271

**Comment by TomTomRixRix** [comment]
`simpa_tests/manual_tests/digital_device_twins/SimulationWithMSOTInvision.py` also doesn't work

**Comment by faberno** [comment]
There are still some rot90 left in simpa, mostly in the plotting functions and some tests (also in KWaveAcousticForwardConvenienceFunction, which is one reason why the output looks so strange). We should probably replace them too :D

**Comment by TomTomRixRix** [comment]
> There are still some rot90 left in simpa, mostly in the plotting functions and some tests (also in KWaveAcousticForwardConvenienceFunction, which is one reason why the output looks so strange). We should probably replace them too :D

You were right, the rot90 error was also a problem in the `KWaveAcousticForwardConvenienceFunction` test. Furthermore the field of view and the spacing needed to be set in order to have a visually similar reconstruction. Now #271 should also be fixed.

**Review by jgroehl — APPROVED** [review]

**Pull request merged**
