### PR TITLE
PathManager refactoring

### LINKED ISSUE #294: Path names and management
Currently, path management is doe through the class `PathManager`. The path names are, however, too generic, such as `SAVE_PATH`, which can lead to clashes with other packages or variables.

**Solution**
Disambiguate paths by prepending `SIMPA_` to them. In addition, it should be allowed for the variables to be loaded directly from the environment, without having to define a `.env` file.

### PR DESCRIPTION
**Pull request by leoyala**
`PathManager` now accepts environment variables being defined by the user and not through a .env file. 

In summary: 
- Removed `FileNotFound` raise from `PathManager` and replaced with `KeyError` only when querying the variables through `get_...`
- Removed tests that checked for `FileNotFound` being raised
- Added Tags for the variable names that `simpa` expects
- Added short instructions to CONTRIBUTING guidelines

 Fixes #294

### CODE REVIEW

**Comment by jgroehl** [comment]
I am wondering why the target branch for this pull request is `main` even though it seems to be based off the `develop` branch?
Can we change the target to `develop`, or first integrate the current `develop` into `main`?
@kdreher what do you think?

**Comment by leoyala** [comment]
I updated the target to `develop`, I think that is a cleaner solution. We can configure which branch is the default target for merge requests, currently it seems to be `main`, but I believe that we should probably make it `develop` instead.

**Review by TomTomRixRix — APPROVED** [review]
Looks good to me 👍 
Didn't run any tests though

**Comment by jnoelke** [comment]
Since we also have `docs/source` in the repository we should update it with the changes made in the `readme.md`. Especially the file `docs/source/introduction.md` should be updated by building the documentation and then committing the file.

**Pull request merged**
